server:
  port: 8089
spring:
  application:
    name: "productManagement"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
springdoc:
  swagger-ui:
    path: /swagger-ui.html  # <- esto te permite usar http://localhost:8089/swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs       # <- endpoint JSON de OpenAPI

rabbit:
  mq:
    input-queue: "INT_STOCK.QUEUE.REQ"
    input-concurrency: 1
    output-concurrency: 1
    output-queue: "OUT_PURCHASE_ORDER.QUEUE.RES"






